spring.application.name=warehouse


spring.datasource.url=jdbc:h2:file:/Users/loges/Desktop/warehouse-DB/Warehouse_Data
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
